resolvers += Resolver.bintrayIvyRepo("hmrc", "sbt-plugin-releases")
resolvers += Resolver.bintrayRepo("hmrc", "releases")
resolvers += Resolver.typesafeRepo("releases")

addSbtPlugin("com.iheart"        % "sbt-play-swagger"      % "0.10.2")
addSbtPlugin("com.lucidchart"    % "sbt-scalafmt"          % "1.16")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"           % "0.5.1")
addSbtPlugin("com.typesafe.play" % "sbt-plugin"            % "2.7.7")
addSbtPlugin("org.scalastyle"    % "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"         % "1.6.1")
addSbtPlugin("org.wartremover"   % "sbt-wartremover"       % "2.4.13")
addSbtPlugin("uk.gov.hmrc"       % "sbt-auto-build"        % "2.11.0")
addSbtPlugin("uk.gov.hmrc"       % "sbt-bobby"             % "3.2.0")
addSbtPlugin("uk.gov.hmrc"       % "sbt-distributables"    % "2.1.0")
addSbtPlugin("uk.gov.hmrc"       % "sbt-git-versioning"    % "2.2.0")
addSbtPlugin("uk.gov.hmrc"       % "sbt-service-manager"   % "0.8.0")
